---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: {{ .Values.name }}
  labels:
    service-name: {{ .Values.service_name }}
spec:
  workspaces:
    - name: shared-workspace
    - name: maven-settings
  params:
  - name: APPLICATION_NAME
    type: string
    default: ""
  - name: GIT_URL
    type: string
    default: ""
  - name: GIT_REVISION
    type: string
    default: "main"
  - name: GIT_REF
    type: string
    default: "refs/heads/main"
  - name: GIT_BRANCH
    type: string
    default: ""
  - name: GIT_SHA
    type: string
    default: ""
  tasks:
    - name: fetch-app-repository
      taskRef:
        name: git-clone
        kind: ClusterTask
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: "$(params.GIT_URL)"
        - name: revision
          value: "main"
        - name: subdirectory
          value: "$(params.APPLICATION_NAME)/$(params.GIT_BRANCH)"
        - name: deleteExisting
          value: "true"
    - name: fetch-gitops-repository
      taskRef:
        name: git-clone
        kind: ClusterTask
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: "https://github.com/justindav1s/residency-gitops.git"
        - name: revision
          value: "main"
        - name: subdirectory
          value: "$(params.APPLICATION_NAME)-gitops"
        - name: deleteExisting
          value: "true"
    - name: get-version
      taskRef:
        name: get-version
        kind: ClusterTask
      runAfter:
         - fetch-app-repository
         - fetch-gitops-repository
      workspaces:
        - name: maven-settings
          workspace: maven-settings
        - name: output
          workspace: shared-workspace
      params:
        - name: WORK_DIRECTORY
          value: "$(params.APPLICATION_NAME)/$(params.GIT_BRANCH)"
        - name: GIT_SHA
          value: "$(params.GIT_SHA)"
    - name: maven
      taskRef:
        name: maven
        kind: ClusterTask
      runAfter:
         - fetch-app-repository
      params:
        - name: MAVEN_IMAGE
          value: "registry.access.redhat.com/ubi8/openjdk-17:latest"
        - name: GOALS
          value:
            - "-U"
            - "-B"
            - "-q"
            - "package"
        - name: CONTEXT_DIR
          value: "$(params.APPLICATION_NAME)/$(params.GIT_BRANCH)"
      workspaces:
        - name: maven-settings
          workspace: maven-settings
        - name: source
          workspace: shared-workspace
    - name: bake
      taskRef:
        name: bake
        kind: ClusterTask
      runAfter:
        - maven
        - get-version 
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: APPLICATION_NAME
          value: "$(params.APPLICATION_NAME)"
        - name: WORK_DIRECTORY
          value: "$(params.APPLICATION_NAME)/$(params.GIT_BRANCH)"
        - name: VERSION
          value: "$(tasks.get-version.results.VERSION)"
    - name: helm-package
      taskRef:
        name: helm-package
        kind: ClusterTask
      runAfter:
        - maven
        - get-version 
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: APPLICATION_NAME
          value: "$(params.APPLICATION_NAME)"
        - name: WORK_DIRECTORY
          value: "$(params.APPLICATION_NAME)/$(params.GIT_BRANCH)"
        - name: CHART_VERSION
          value: "$(tasks.get-version.results.CHART_VERSION)"
    - name: deploy-test
      taskRef:
        name: deploy
        kind: ClusterTask
      runAfter:
        - bake
        - helm-package
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: APPLICATION_NAME
          value: "$(params.APPLICATION_NAME)"
        - name: WORK_DIRECTORY
          value: "$(params.APPLICATION_NAME)-gitops"
        - name: VERSION
          value: "$(tasks.get-version.results.VERSION)"
        - name: CHART_VERSION
          value: "$(tasks.get-version.results.CHART_VERSION)"
        - name: DEPLOY_ENVIRONMENT
          value: "test"
        - name: GITOPS_CONFIG_REPOSITORY_NAME
          value: "{{ .Values.gitops_repo }}"
        - name: GITOPS_SERVICE_DIRECTORY
          value: "{{ .Values.service_name }}"

  results:
    - name: VERSION
      description: Version of the application
      value: "$(tasks.get-version.results.VERSION)"
    - name: CHART_VERSION
      description: Version of the helm chart
      value: "$(tasks.get-version.results.CHART_VERSION)"
    - name: PREVIOUS_VERSION
      description: Version of the application
      value: "$(tasks.deploy-test.results.PREVIOUS_VERSION)"
    - name: PREVIOUS_CHART_VERSION
      description: Version of the helm chart
      value: "$(tasks.deploy-test.results.PREVIOUS_CHART_VERSION)"
