apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: {{ include "spring-boot.fullname" . }}-helm-repo
spec:
  interval: 1m
  url: https://gitlab.com/demoplatform/helmcharts/-/raw/main/charts/