---
apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: dev-mesh
spec:
  security:
    controlPlane:
      mtls: true
    dataPlane:
      mtls: true
      automtls: true
  tracing:
    sampling: 10000
    type: Jaeger
  general:
    logging:
      logAsJSON: true
  profiles:
    - default
  proxy:
    accessLogging:
      file:
        name: /dev/stdout
    networking:
      trafficControl:
        inbound: {}
        outbound:
          policy: ALLOW_ANY
  policy:
    type: Istiod
  addons:
    grafana:
      enabled: true
    jaeger:
      install:
        storage:
          type: Memory
    kiali:
      enabled: true
    prometheus:
      enabled: true
  runtime:
    components:
      pilot:
        deployment:
          autoScaling:
            enabled: true
            maxReplicas: 1
            minReplicas: 1
  version: v2.1
  telemetry:
    type: Istiod
