apiVersion: v1
version: 1.0.12
appVersion: 1.0.12
name: microservice
description: MicroService Helm chart for Kubernetes
home: https://github.com/justindav1s/helmcharts
maintainers:
- email: justindav1s@users.noreply.github.com
  name: justindav1s
sources:
- https://github.com/justindav1s/helmcharts
