---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.name }}-sa
secrets:
- name: git-auth
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.name }}-sa-role
rules:
  - apiGroups:
      - 'build.openshift.io'
    resources:
      - '*'
    verbs:
      - '*'
  - apiGroups:
      - 'tekton.dev'
    resources:
      - '*'
    verbs:
      - '*'
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.name }}-sa-rb
subjects:
  - kind: ServiceAccount
    name: {{ .Values.name }}-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.name }}-sa-role
