{{- $cluster := .Values.kafka.cluster_name }}
{{- range $key := .Values.topics }}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: {{ .name }}
  labels:
    strimzi.io/cluster: {{ $cluster }}
spec:
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824
  partitions: {{ .partitions | default "10" }}
  replicas: {{ .replicas | default "3" }}
{{- end }}