{{- $cluster := .Values.kafka.cluster_name }}
{{- range $key := .Values.users }}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  labels:
    strimzi.io/cluster: {{ $cluster }}
  name: {{ .name }}
spec:
  authentication:
    type: tls
{{- end }}    