---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: {{ .Values.kafka.cluster_name }}
spec:
  entityOperator:
    topicOperator: {}
    userOperator: {}
  kafka:
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      inter.broker.protocol.version: '3.1'
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    {{- if .Values.route }}
      - name: external
        port: 9094
        tls: true
        type: route
      - name: mtls
        authentication:
          enablePlain: true
          type: tls
        name: mtls
        port: 9095
        tls: true
        type: route         
    {{- end }}
    replicas: {{ .Values.kafka.broker.replicas }}
    storage:
      type: persistent-claim
      size: {{ .Values.kafka.storage.size }}
    version: 3.1.0
  zookeeper:
    replicas: {{ .Values.kafka.zookeeper.replicas }}
    storage:
      type: persistent-claim
      size: {{ .Values.kafka.zookeeper.storage.size }}