---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: {{ .Values.name }}-github-webhook
  labels:
    app: github
spec:
  namespaceSelector: {}
  resources: {}
  serviceAccountName: pipeline
  triggers:
  - bindings:
    - kind: TriggerBinding
      ref: {{ .Values.name }}-maven-github-trigger-binding
    interceptors:
    - params:
      - name: filter
        value: (header.match('X-GitHub-Event', 'push') && body.ref.split('/')[2] == 'main')
      - name: overlays
        value:
        - expression: body.ref.split('/')[2]
          key: branch_name
      ref:
        kind: ClusterInterceptor
        name: cel
    name: {{ .Values.name }}-github-webhook
    template:
      ref: {{ .Values.name }}-maven-trigger-template
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.name }}-webhook
  labels:
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: {{ .Values.name }}-github-webhook
spec:
  port:
    targetPort: http-listener
  to:
    kind: 'Service'
    name: el-{{ .Values.name }}-github-webhook
    weight: 100
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge