---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: {{ .Values.name }}-maven-github-trigger-binding
spec:
  params:
    - name: git-repo-name
      value: $(body.repository.name)
    - name: git-revision
      value: $(body.commits.id)
    - name: git-ref
      value: $(body.ref)
    - name: git-branch
      value: $(extensions.branch_name)
    - name: git-sha
      value: $(body.after)
