---
apiVersion: operator.tekton.dev/v1alpha1
kind: TektonConfig
metadata:
  name: config
spec:
  addon:
    enablePipelinesAsCode: true
    params:
      - name: clusterTasks
        value: 'true'
      - name: pipelineTemplates
        value: 'true'
      - name: communityClusterTasks
        value: 'true'
  pipeline:
    running-in-environment-with-injected-sidecars: true
    metrics.taskrun.duration-type: histogram
    metrics.pipelinerun.duration-type: histogram
    params:
      - name: enableMetrics
        value: 'true'
    default-service-account: pipeline
    scope-when-expressions-to-task: false
    require-git-ssh-secret-known-hosts: false
    enable-tekton-oci-bundles: false
    metrics.taskrun.level: task
    metrics.pipelinerun.level: pipeline
    enable-api-fields: alpha
    enable-custom-tasks: false
    disable-creds-init: false
    disable-affinity-assistant: true
  config: {}
  params:
    - name: createRbacResource
      value: 'true'
  pruner:
    keep: {{ .Values.pruner.keep }}
    resources:
      - pipelinerun
    schedule: {{ .Values.pruner.schedule | quote }}
  profile: all
  targetNamespace: openshift-pipelines
  dashboard:
    readonly: false
  hub: {}
  trigger:
    default-service-account: pipeline
    enable-api-fields: stable