apiVersion: v1
entries:
  base:
  - apiVersion: v1
    created: "2021-06-18T10:35:08.979132+01:00"
    description: Helm chart for deploying Istio cluster resources and CRDs
    digest: d76d6a68d90859f117b0e6d8fababff2fe2fa729ba191fe0850c679e2996fc7b
    icon: https://istio.io/latest/favicons/android-192x192.png
    keywords:
    - istio
    name: base
    sources:
    - http://github.com/istio/istio
    urls:
    - base-1.1.0.tgz
    version: 1.1.0
  istio-cni:
  - apiVersion: v1
    created: "2021-06-18T10:35:08.98026+01:00"
    description: Helm chart for istio-cni components
    digest: 923dcddc32066b2a9b1131df7707eb2d59d8865580b91b5533483a9da1601667
    icon: https://istio.io/latest/favicons/android-192x192.png
    keywords:
    - istio-cni
    - istio
    name: istio-cni
    sources:
    - http://github.com/istio/cni
    urls:
    - istio-cni-1.1.0.tgz
    version: 1.1.0
  istio-discovery:
  - apiVersion: v1
    created: "2021-06-18T10:35:08.982316+01:00"
    description: Helm chart for istio control plane
    digest: 07df61d623a5489cfb007b9b2c2820390ca1bf2d9f46a8ffbce49b6e84e7fab4
    icon: https://istio.io/latest/favicons/android-192x192.png
    keywords:
    - istio
    - istiod
    - istio-discovery
    name: istio-discovery
    sources:
    - http://github.com/istio/istio
    urls:
    - istio-discovery-1.2.0.tgz
    version: 1.2.0
  istio-ingress:
  - apiVersion: v1
    created: "2021-06-18T10:35:08.983393+01:00"
    description: Helm chart for deploying Istio gateways
    digest: 2ef4c854f8722b385bdfa2b0837d5f1153243136193dfb2272c86fcc086401f0
    icon: https://istio.io/latest/favicons/android-192x192.png
    keywords:
    - istio
    - ingressgateway
    - gateways
    name: istio-ingress
    sources:
    - http://github.com/istio/istio
    urls:
    - istio-ingress-1.1.0.tgz
    version: 1.1.0
  istio-operator:
  - apiVersion: v1
    created: "2021-06-18T10:35:08.983769+01:00"
    description: Helm chart for deploying Istio operator
    digest: 70c8e68b732cfb88db91bc03811741b044d91215895dfc39c5a1eeec87844ed0
    icon: https://istio.io/latest/favicons/android-192x192.png
    keywords:
    - istio
    - operator
    name: istio-operator
    sources:
    - https://github.com/istio/istio/tree/master/operator
    urls:
    - istio-operator-1.7.0.tgz
    version: 1.7.0
  microservice:
  - apiVersion: v1
    appVersion: 1.0.17
    created: "2021-06-18T10:35:08.985694+01:00"
    description: MicroService Helm chart for Kubernetes
    digest: 52b780bc5e42f1926bb3a64ced3671b14bb5722dc7f8e2b7c2d00bf44b51fae0
    home: https://gitlab.com/demoplatform/helmcharts
    maintainers:
    - email: justinndavis@gmail.com
      name: justinndavis
    name: microservice
    sources:
    - https://gitlab.com/demoplatform/helmcharts
    urls:
    - microservice-1.0.17.tgz
    version: 1.0.17
  - apiVersion: v1
    appVersion: 1.0.16
    created: "2021-06-18T10:35:08.985358+01:00"
    description: MicroService Helm chart for Kubernetes
    digest: e1917e4422f4dc0e901de263d94e050dad969527ea732a41610abbc8054190ef
    home: https://gitlab.com/demoplatform/helmcharts
    maintainers:
    - email: justinndavis@gmail.com
      name: justinndavis
    name: microservice
    sources:
    - https://gitlab.com/demoplatform/helmcharts
    urls:
    - microservice-1.0.16.tgz
    version: 1.0.16
  - apiVersion: v1
    appVersion: 1.0.15
    created: "2021-06-18T10:35:08.985057+01:00"
    description: MicroService Helm chart for Kubernetes
    digest: 1d5ec5a1769bb1940e032f2f192462a2c589c98b8a31ff99556c373f50d7cfca
    home: https://gitlab.com/demoplatform/helmcharts
    maintainers:
    - email: justinndavis@gmail.com
      name: justinndavis
    name: microservice
    sources:
    - https://gitlab.com/demoplatform/helmcharts
    urls:
    - microservice-1.0.15.tgz
    version: 1.0.15
  - apiVersion: v1
    appVersion: 1.0.14
    created: "2021-06-18T10:35:08.984736+01:00"
    description: MicroService Helm chart for Kubernetes
    digest: 898229e7c44062268f248445cc00a0417801619129de6985fa4f8663f38e9c22
    home: https://gitlab.com/demoplatform/helmcharts
    maintainers:
    - email: justinndavis@gmail.com
      name: justinndavis
    name: microservice
    sources:
    - https://gitlab.com/demoplatform/helmcharts
    urls:
    - microservice-1.0.14.tgz
    version: 1.0.14
  - apiVersion: v1
    appVersion: 1.0.13
    created: "2021-06-18T10:35:08.984439+01:00"
    description: MicroService Helm chart for Kubernetes
    digest: 0d24e2b1c811eefaa814a32d20516aa479f50974cfca8d3effe8fad897430033
    home: https://gitlab.com/demoplatform/helmcharts
    maintainers:
    - email: justinndavis@gmail.com
      name: justinndavis
    name: microservice
    sources:
    - https://gitlab.com/demoplatform/helmcharts
    urls:
    - microservice-1.0.13.tgz
    version: 1.0.13
  - apiVersion: v1
    appVersion: 1.0.12
    created: "2021-06-18T10:35:08.984126+01:00"
    description: MicroService Helm chart for Kubernetes
    digest: ab1ec0346e52178165e7c4c5cf8180f99d9597932d94663947b9f205294f162a
    home: https://gitlab.com/demoplatform/helmcharts
    maintainers:
    - email: justinndavis@gmail.com
      name: justinndavis
    name: microservice
    sources:
    - https://gitlab.com/demoplatform/helmcharts
    urls:
    - microservice-1.0.12.tgz
    version: 1.0.12
  spring-boot:
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2021-06-18T10:35:08.987885+01:00"
    description: A Helm chart for Spring Boot on Kubernetes
    digest: 7fc3caaf774a7fe644899b69749cb040a55e3043ba47a8840939755e05ef0b57
    name: spring-boot
    type: application
    urls:
    - spring-boot-1.2.0.tgz
    version: 1.2.0
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2021-06-18T10:35:08.987375+01:00"
    description: A Helm chart for Spring Boot on Kubernetes
    digest: 19dca415d21a4b04498b8222c4ffc6f42cfcfbf1dbadb4b30f8290e418d467ee
    name: spring-boot
    type: application
    urls:
    - spring-boot-1.1.1.tgz
    version: 1.1.1
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2021-06-18T10:35:08.986834+01:00"
    description: A Helm chart for Spring Boot on Kubernetes
    digest: 4b6499d1e23154da55a4d4ba06bed6c2a6e8ae00d9de73919cbdcbc93c318324
    name: spring-boot
    type: application
    urls:
    - spring-boot-1.1.0.tgz
    version: 1.1.0
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2021-06-18T10:35:08.986274+01:00"
    description: A Helm chart for Spring Boot on Kubernetes
    digest: 1d0ad6dec08c74684ed04c8e88abfc02cc8368ec8f09e0611770344aab0995d9
    name: spring-boot
    type: application
    urls:
    - spring-boot-1.0.0.tgz
    version: 1.0.0
generated: "2021-06-18T10:35:08.976923+01:00"
