apiVersion: v1
entries:
  microservice:
  - apiVersion: v1
    appVersion: 1.0.15
    created: "2021-06-11T10:17:38.131269+01:00"
    description: MicroService Helm chart for Kubernetes
    digest: 1d5ec5a1769bb1940e032f2f192462a2c589c98b8a31ff99556c373f50d7cfca
    home: https://gitlab.com/demoplatform/helmcharts
    maintainers:
    - email: justinndavis@gmail.com
      name: justinndavis
    name: microservice
    sources:
    - https://gitlab.com/demoplatform/helmcharts
    urls:
    - microservice-1.0.15.tgz
    version: 1.0.15
  - apiVersion: v1
    appVersion: 1.0.14
    created: "2021-06-11T10:17:38.130954+01:00"
    description: MicroService Helm chart for Kubernetes
    digest: 898229e7c44062268f248445cc00a0417801619129de6985fa4f8663f38e9c22
    home: https://gitlab.com/demoplatform/helmcharts
    maintainers:
    - email: justinndavis@gmail.com
      name: justinndavis
    name: microservice
    sources:
    - https://gitlab.com/demoplatform/helmcharts
    urls:
    - microservice-1.0.14.tgz
    version: 1.0.14
  - apiVersion: v1
    appVersion: 1.0.13
    created: "2021-06-11T10:17:38.130623+01:00"
    description: MicroService Helm chart for Kubernetes
    digest: 0d24e2b1c811eefaa814a32d20516aa479f50974cfca8d3effe8fad897430033
    home: https://gitlab.com/demoplatform/helmcharts
    maintainers:
    - email: justinndavis@gmail.com
      name: justinndavis
    name: microservice
    sources:
    - https://gitlab.com/demoplatform/helmcharts
    urls:
    - microservice-1.0.13.tgz
    version: 1.0.13
  - apiVersion: v1
    appVersion: 1.0.12
    created: "2021-06-11T10:17:38.130088+01:00"
    description: MicroService Helm chart for Kubernetes
    digest: ab1ec0346e52178165e7c4c5cf8180f99d9597932d94663947b9f205294f162a
    home: https://gitlab.com/demoplatform/helmcharts
    maintainers:
    - email: justinndavis@gmail.com
      name: justinndavis
    name: microservice
    sources:
    - https://gitlab.com/demoplatform/helmcharts
    urls:
    - microservice-1.0.12.tgz
    version: 1.0.12
  spring-boot:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2021-06-11T10:17:38.134505+01:00"
    description: A Helm chart for Spring Boot on Kubernetes
    digest: 7ced4c613b04f2f2947da09b54683b7ae1909d2e4718e261a99575aef2de535c
    name: spring-boot
    type: application
    urls:
    - spring-boot-0.1.2.tgz
    version: 0.1.2
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2021-06-11T10:17:38.132607+01:00"
    description: A Helm chart for Spring Boot on Kubernetes
    digest: 7cd6fc3b3f7c15f0c1c347504a16ef9c379a45b4c0bf6f41a67f93f8d1077969
    name: spring-boot
    type: application
    urls:
    - spring-boot-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2021-06-11T10:17:38.131827+01:00"
    description: A Helm chart for Kubernetes
    digest: acc18bd090a1b17401a8ff52501cb11552a626ad9f126607dd65867e4d393d8f
    name: spring-boot
    type: application
    urls:
    - spring-boot-0.1.0.tgz
    version: 0.1.0
generated: "2021-06-11T10:17:38.129132+01:00"
