kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-config
  labels:
    service: {{ .Release.Name }}
    app: {{ .Values.applabel }}
    version: {{ .Values.versionlabel }}  
data:
  config.dev.properties: |
    my.property=hello
    sleep.time.ms=0
    {{ .Release.Name }}.version=dev
    anotherthing=true
    anotherthing2=true