kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ .Release.Name }}
  labels:
    service: {{ .Release.Name }}
    app: {{ .Values.applabel }}
    version: {{ .Values.versionlabel }} 
spec:
  to:
    kind: Service
    name: {{ .Release.Name }}
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
