---
apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: {{ .Values.name }}-get-version
spec:
  workspaces:
    - name: output
  params:
    - name: WORK_DIRECTORY
      description: Directory to start build in (handle multiple branches)
      type: string
    - name: GIT_SHA
      description: Git commit sha
      type: string
  results:
    - name: VERSION
      description: Version of the application
    - name: CHART_VERSION
      description: Version of the helm chart
  steps:
    - name: get-app-version
      image: registry.access.redhat.com/ubi8/openjdk-17:latest
      workingDir: $(workspaces.output.path)/$(params.WORK_DIRECTORY)
      command: ["/bin/sh", "-c"]
      args:
        - echo -n $(mvn -s $(workspaces.maven-settings.path)/settings.xml help:evaluate -Dexpression=project.version -q -DforceStdout)-$(echo $(params.GIT_SHA) | head -c7) | xargs echo -n | tee $(results.VERSION.path)
    - name: get-helm-chart-version
      image: quay.io/redhat-cop/tekton-task-helm:3.6.3
      workingDir: $(workspaces.output.path)/$(params.WORK_DIRECTORY)
      command: ["/bin/sh", "-c"]
      args: 
        - "echo -n `helm show chart chart | grep version: | awk '{print $2}'`-$(echo $(params.GIT_SHA) | head -c7) | tee $(results.CHART_VERSION.path);"
  workspaces:
    - name: output
      description: The workspace consisting of maven project.
    - name: maven-settings
      description: >-
        The workspace consisting of the custom maven settings provided by the
        user.
