---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-maven-settings
data: 
  settings.xml: |-
    <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                          http://maven.apache.org/xsd/settings-1.0.0.xsd">

      <activeProfiles>
        <activeProfile>maven-public</activeProfile>
        <activeProfile>github</activeProfile>
      </activeProfiles>

      <profiles>
        <profile>
          <id>maven-public</id>
          <repositories>
            <!-- <repository>
              <id>dynamodb-local</id>
              <url>https://s3-us-west-2.amazonaws.com/dynamodb-local/release</url>
            </repository> -->
            <repository>
              <id>maven-public</id>
              <url>http://nexus.labs-ci-cd.svc.cluster.local:8081/repository/maven-public/</url>
            </repository>
          </repositories>
          <pluginRepositories>
            <pluginRepository>
              <id>maven-public</id>
              <url>http://nexus.labs-ci-cd.svc.cluster.local:8081/repository/maven-public/</url>
            </pluginRepository>
          </pluginRepositories>
        </profile>
        <profile>
          <id>github</id>
            <repositories>
              <repository>
                <id>github</id>
                <url>https://maven.pkg.github.com/justindav1s/maven</url>
              </repository>
            </repositories>
        </profile>
      </profiles>
      <servers>
        <server>
          <id>maven-public</id>
          <username>admin</username>
          <password>admin123</password>
        </server>
        <server>
          <id>github</id>
          <username>${repo.login}</username>
          <password>${repo.pwd}</password>
        </server>
      </servers>

    </settings>
